### ISSUE TITLE
ModuleNotFoundError: No module named 'albumentations'

### ISSUE THREAD

**Issue by JoaoMosmann** [Thomasbehan/SkinVestigatorAI#10]
**Describe the bug**
Following the **Running the Application without Docker** steps, while trying to run the application, I'm presented with the error 
`ModuleNotFoundError: No module named 'albumentations'`

**To Reproduce**
1. Follow the **Running the Application without Docker** steps
2. By the end, run `env/bin/pserve development.ini`

**Expected behavior**
Application should run

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1 (22E261)
 - Python: 3.11.3
 - Arch: Arm64

**Comment by Thomasbehan** [comment]
Hey Joao, Check out the PR I submitted I think it should fix the issue you're getting. Let me know if it fixes it for you.

**Comment by Thomasbehan** [comment]
Hey @JoaoMosmann this issue auto closed with the merge just wanted to check if the issue is solved for Macs with apple silicon if not let me know 🙂

**Comment by JoaoMosmann** [comment]
Haven't had the time to build tensorflow from source.

I've tried going the Docker path, but I'm getting the following error
```
#0 35.57 Installed /usr/local/lib/python3.9/dist-packages/Markdown-3.4.3-py3.9.egg
#0 35.57 Searching for grpcio>=1.48.2
#0 35.57 Reading https://pypi.org/simple/grpcio/
#0 37.75 Downloading https://files.pythonhosted.org/packages/ef/e4/5c717f3c6c65b7c5ff2542ca25d6c2ce0f99d9ee9119620c6e2325a6da79/grpcio-1.54.0.tar.gz#sha256=eb0807323572642ab73fd86fe53d88d843ce617dd1ddf430351ad0759809a0ae
#0 38.87 Best match: grpcio 1.54.0
#0 38.87 Processing grpcio-1.54.0.tar.gz
#0 39.49 Writing /tmp/easy_install-bmipv3mm/grpcio-1.54.0/setup.cfg
#0 39.49 Running grpcio-1.54.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bmipv3mm/grpcio-1.54.0/egg-dist-tmp-tcoxvgkr
#0 39.60 error: [Errno 2] No such file or directory: 'c++'
```
This weekend I'll try running it on my Windows/Nvidia envinronment.
